/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kafka.coordinator.common.runtime;

import org.apache.kafka.common.KafkaException;
import org.apache.kafka.common.TopicPartition;
import org.apache.kafka.common.requests.TransactionResult;

import java.util.List;
import java.util.OptionalInt;
import java.util.concurrent.CompletableFuture;

// Based on the last commit ID of trunk: 5f0e368255b6c3638a7502ea787eed17ca69cf18
public interface ICoordinatorRuntime<S extends CoordinatorShard<U>, U> extends AutoCloseable {

    /**
     * A coordinator write operation.
     *
     * @param <S> The type of the coordinator state machine.
     * @param <T> The type of the response.
     * @param <U> The type of the records.
     */
    interface CoordinatorWriteOperation<S, T, U> {
        /**
         * Generates the records needed to implement this coordinator write operation. In general,
         * this operation should not modify the hard state of the coordinator. That modifications
         * will happen later on, when the records generated by this function are applied to the
         * coordinator.
         *
         * @param coordinator The coordinator state machine.
         * @return A result containing a list of records and the RPC result.
         * @throws KafkaException
         */
        CoordinatorResult<T, U> generateRecordsAndResult(S coordinator) throws KafkaException;
    }

    /**
     * A coordinator read operation.
     *
     * @param <S> The type of the coordinator state machine.
     * @param <T> The type of the response.
     */
    interface CoordinatorReadOperation<S, T> {
        /**
         * Generates the response to implement this coordinator read operation. A read
         * operation received the last committed offset. It must use it to ensure that
         * it does not read uncommitted data from the timeline data structures.
         *
         * @param state  The coordinator state machine.
         * @param offset The last committed offset.
         * @return A response.
         * @throws KafkaException
         */
        T generateResponse(S state, long offset) throws KafkaException;
    }


    /**
     * Schedules a write operation.
     *
     * @param name The name of the write operation.
     * @param tp   The address of the coordinator (aka its topic-partitions).
     * @param op   The write operation.
     * @param <T>  The type of the result.
     * @return A future that will be completed with the result of the write operation
     * when the operation is completed or an exception if the write operation failed.
     */
    <T> CompletableFuture<T> scheduleWriteOperation(
            String name,
            TopicPartition tp,
            CoordinatorWriteOperation<S, T, U> op
    );

    /**
     * Schedules a read operation for each coordinator.
     *
     * @param name The name of the read operation.
     * @param op   The read operation.
     * @param <T>  The type of the result.
     * @return A list of futures where each future will be completed with the result of the read operation
     * when the operation is completed or an exception if the read operation failed.
     */
    <T> List<CompletableFuture<T>> scheduleReadAllOperation(
            String name,
            CoordinatorReadOperation<S, T> op
    );

    /**
     * Schedules a transactional write operation.
     *
     * @param name            The name of the write operation.
     * @param tp              The address of the coordinator (aka its topic-partitions).
     * @param transactionalId The transactional id.
     * @param producerId      The producer id.
     * @param producerEpoch   The producer epoch.
     * @param op              The write operation.
     * @param apiVersion      The Version of the Txn_Offset_Commit request
     * @param <T>             The type of the result.
     * @return A future that will be completed with the result of the write operation
     * when the operation is completed or an exception if the write operation failed.
     */
    <T> CompletableFuture<T> scheduleTransactionalWriteOperation(
            String name,
            TopicPartition tp,
            String transactionalId,
            long producerId,
            short producerEpoch,
            CoordinatorRuntime.CoordinatorWriteOperation<S, T, U> op,
            int apiVersion
    );

    /**
     * Schedules the transaction completion.
     *
     * @param name               The name of the operation.
     * @param tp                 The address of the coordinator (aka its topic-partitions).
     * @param producerId         The producer id.
     * @param producerEpoch      The producer epoch.
     * @param coordinatorEpoch   The epoch of the transaction coordinator.
     * @param result             The transaction result.
     * @param transactionVersion The transaction version (1 = TV1, 2 = TV2, etc.).
     * @return A future that will be completed with null when the operation is
     * completed or an exception if the operation failed.
     */
    CompletableFuture<Void> scheduleTransactionCompletion(
            String name,
            TopicPartition tp,
            long producerId,
            short producerEpoch,
            int coordinatorEpoch,
            TransactionResult result,
            short transactionVersion
    );


    /**
     * Schedules the loading of a coordinator. This is called when the broker is elected as
     * the leader for a partition.
     *
     * @param tp             The topic partition of the coordinator. Records from this
     *                       partitions will be read and applied to the coordinator.
     * @param partitionEpoch The epoch of the partition.
     */
    void scheduleLoadOperation(
            TopicPartition tp,
            int partitionEpoch
    );

    /**
     * Schedules the unloading of a coordinator. This is called when the broker is not the
     * leader anymore.
     *
     * @param tp             The topic partition of the coordinator.
     * @param partitionEpoch The partition epoch as an optional value.
     *                       An empty value means that the topic was deleted.
     */
    void scheduleUnloadOperation(
            TopicPartition tp,
            OptionalInt partitionEpoch
    );

    /**
     * A new metadata image is available.
     *
     * @param delta    The metadata delta.
     * @param newImage The new metadata image.
     */
    void onMetadataUpdate(
            CoordinatorMetadataDelta delta,
            CoordinatorMetadataImage newImage
    );

    /**
     * Schedule a write operation for each coordinator.
     *
     * @param name The name of the write operation.
     * @param op   The write operation.
     * @param <T>  The type of the result.
     * @return A list of futures where each future will be completed with the result of the write operation
     * when the operation is completed or an exception if the write operation failed.
     */
    <T> List<CompletableFuture<T>> scheduleWriteAllOperation(
            String name,
            CoordinatorWriteOperation<S, T, U> op
    );

    /**
     * Schedules a read operation.
     *
     * @param name The name of the read operation.
     * @param tp   The address of the coordinator (aka its topic-partitions).
     * @param op   The read operation.
     * @param <T>  The type of the result.
     * @return A future that will be completed with the result of the read operation
     * when the operation is completed or an exception if the read operation failed.
     */
    <T> CompletableFuture<T> scheduleReadOperation(
            String name,
            TopicPartition tp,
            CoordinatorReadOperation<S, T> op
    );

    /**
     * @return List of {@link TopicPartition} whose coordinators are active.
     */
    List<TopicPartition> activeCoordinators();
}
